SELECT ITMSC.CODE AS ITEMSCODE, ITMSC.NAME, LGMAIN.CLIENTCODE AS CARIKOD, CLNTC.DEFINITION_, LGMAIN.PRICE, UNITBCODE.BARCODE
--LGMAIN.LOGICALREF, LGMAIN.CODE, LGMAIN.GRPCODE, LGMAIN.ORDERNR,  LGMAIN.CLSPECODE, 
--LGMAIN.SHIPTYP, LGMAIN.DEFINITION_, LGMAIN.BEGDATE, LGMAIN.ENDDATE, LGMAIN.PTYPE, LGMAIN.INCVAT, LGMAIN.UOMREF, LGMAIN.CARDREF, 
--LGMAIN.MTRLTYPE, LGMAIN.CURRENCY, LGMAIN.PAYPLANREF, LGMAIN.ORGLOGICREF,  LGMAIN.CYPHCODE, LGMAIN.ACTIVE, 
--LGMAIN.WFLOWCRDREF, LGMAIN.BRANCH, LGMAIN.EXTACCESSFLAGS,  ITMSC.NAME3, ITMSC.NAME4, 
FROM LG_335_PRCLIST LGMAIN WITH(NOLOCK) LEFT OUTER JOIN LG_335_CLCARD CLNTC WITH(NOLOCK) ON (LGMAIN.CLIENTCODE = CLNTC.CODE) 
LEFT OUTER JOIN LG_335_ITEMS ITMSC WITH(NOLOCK) ON (LGMAIN.CARDREF = ITMSC.LOGICALREF)
--LEFT OUTER JOIN LG_335_ITMUNITA ITMUASGN WITH(NOLOCK) ON (LGMAIN.CARDREF = ITMUASGN.ITEMREF 
--AND ISNULL(ITMUASGN.VARIANTREF, 0) = 0 AND ITMUASGN.UNITLINEREF = LGMAIN.UOMREF)
LEFT OUTER JOIN LG_335_UNITBARCODE UNITBCODE WITH(NOLOCK) ON (LGMAIN.CARDREF = UNITBCODE.ITEMREF 
AND ISNULL(UNITBCODE.VARIANTREF, 0) = 0 AND UNITBCODE.UNITLINEREF = LGMAIN.UOMREF)
WHERE 
--LGMAIN.CLIENTCODE = '1372' AND 
--(LGMAIN.CARDREF = 6) AND
(LGMAIN.ACTIVE = 0) AND (LGMAIN.PTYPE = 2) AND (LGMAIN.MTRLTYPE = 0) AND (ITMSC.ACTIVE = 0) AND ENDDATE >= GETDATE()
ORDER BY LGMAIN.LOGICALREF
