SELECT
    ITMSC.CODE AS ITEMCODE, 
    ITMSC.NAME AS ITEMNAME, --ITMSC.NAME2, ITMSC.NAME3,ITMSC.NAME4, SPC.DEFINITION_, SPC.DEFINITION2, 
    SPC.DEFINITION3 AS ITEMGROUPCODE,
    LGMAIN.CLIENTCODE AS CUSTOMERCODE, 
    CLNTC.DEFINITION_ AS CUSTOMERNAME, 
    LGMAIN.PRICE,
    MAX(CASE WHEN ITMUASGN.CONVFACT1 <> ITMUASGN.CONVFACT2 THEN UNITBCODE.BARCODE END) AS PIECEBARCODE,
    MAX(CASE WHEN ITMUASGN.CONVFACT1 = ITMUASGN.CONVFACT2 THEN UNITBCODE.BARCODE END) AS CARTONBARCODE
FROM LG_335_ITEMS ITMSC WITH(NOLOCK) 
LEFT JOIN LG_335_ITMUNITA ITMUASGN WITH(NOLOCK) 
    ON ITMUASGN.ITEMREF = ITMSC.LOGICALREF AND ISNULL(ITMUASGN.VARIANTREF, 0) = 0
LEFT JOIN LG_335_UNITBARCODE UNITBCODE WITH(NOLOCK) 
    ON UNITBCODE.ITEMREF = ITMSC.LOGICALREF AND UNITBCODE.ITMUNITAREF = ITMUASGN.LOGICALREF 
LEFT JOIN LG_335_PRCLIST LGMAIN WITH(NOLOCK) 
    ON LGMAIN.CARDREF = ITMSC.LOGICALREF AND LGMAIN.ACTIVE = 0 AND LGMAIN.PTYPE = 2
    AND LGMAIN.MTRLTYPE = 0 AND LGMAIN.ENDDATE >= GETDATE()
LEFT JOIN LG_335_CLCARD CLNTC WITH(NOLOCK) 
    ON LGMAIN.CLIENTCODE = CLNTC.CODE AND CLNTC.ACTIVE = 0    
LEFT JOIN LG_335_SPECODES SPC WITH(NOLOCK) 
    ON SPC.SPECODE = ITMSC.STGRPCODE AND SPC.CODETYPE = 4 AND SPC.SPECODETYPE = 0
WHERE ITMSC.ACTIVE = 0 
    --AND ITMSC.CODE = '34818'
	  --AND CLNTC.CODE = '1372' --AND ITMSC.CODE IN ('83729','10032','10100','10117','10124','10131')
GROUP BY 
    --ITMSC.STGRPCODE,
    ITMSC.CODE,
    ITMSC.NAME,
    SPC.DEFINITION3,
    SPC.GLOBALID,
    LGMAIN.CLIENTCODE,
    CLNTC.DEFINITION_,
    LGMAIN.PRICE
	--,ITMSC.NAME2, ITMSC.NAME3,ITMSC.NAME4, SPC.DEFINITION_, SPC.DEFINITION2
ORDER BY TRY_CAST(SPC.GLOBALID AS INT), ITEMNAME
